export const ExceptionTypes = {
  INVALID_FORM: 'INVALID_FORM',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  UPLOAD_FILE_EXCEPTION: 'UPLOAD_FILE_EXCEPTION',
  
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

