export enum PermissionType {
  SUBMIT = 'SUBMIT',

  // User
  UPDATE_ANY_USER = 'UPDATE_ANY_USER',

  // Article
  CREATE_ARTICLE = 'CREATE_ARTICLE',
  UPDATE_OWN_ARTICLE = 'UPDATE_OWN_ARTICLE',
  UPDATE_ANY_ARTICLE = 'UPDATE_ANY_ARTICLE',
  DELETE_OWN_ARTICLE = 'DELETE_OWN_ARTICLE',
  DELETE_ANY_ARTICLE = 'DELETE_ANY_ARTICLE',

  // Problem
  CREATE_PROBLEM = 'CREATE_PROBLEM',
  UPDATE_OWN_PROBLEM = 'UPDATE_OWN_PROBLEM',
  UPDATE_ANY_PROBLEM = 'UPDATE_ANY_PROBLEM',
  DELETE_OWN_PROBLEM = 'DELETE_OWN_PROBLEM',
  DELETE_ANY_PROBLEM = 'DELETE_ANY_PROBLEM',

  // Contest
  CREATE_CONTEST = 'CREATE_CONTEST',
  UPDATE_OWN_CONTEST = 'UPDATE_OWN_CONTEST',
  UPDATE_ANY_CONTEST = 'UPDATE_ANY_CONTEST',
  DELETE_OWN_CONTEST = 'DELETE_OWN_CONTEST',
  DELETE_ANY_CONTEST = 'DELETE_ANY_CONTEST',

  CREATE_CONTEST_SUBMISSION = 'CREATE_CONTEST_SUBMISSION',

  // Tag
  CREATE_TAG = 'CREATE_TAG',
  UPDATE_ANY_TAG = 'UPDATE_ANY_TAG',
  DELETE_ANY_TAG = 'DELETE_ANY_TAG',

  // Role
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ANY_ROLE = 'UPDATE_ANY_ROLE',
  DELETE_ANY_ROLE = 'DELETE_ANY_ROLE',
}
