export enum PermissionType {
  SUBMIT = 'SUBMIT',

  // User
  UPDATE_ANY_USER = 'UPDATE_ANY_USER',

  // Article
  CREATE_ARTICLE = 'CREATE_ARTICLE',
  UPDATE_OWN_ARTICLE = 'UPDATE_OWN_ARTICLE',
  UPDATE_ANY_ARTICLE = 'UPDATE_ANY_ARTICLE',
  DELETE_OWN_ARTICLE = 'DELETE_OWN_ARTICLE',
  DELETE_ANY_ARTICLE = 'DELETE_ANY_ARTICLE',

  // Problem
  CREATE_PROBLEM = 'CREATE_PROBLEM',
  UPDATE_OWN_PROBLEM = 'UPDATE_OWN_PROBLEM',
  UPDATE_ANY_PROBLEM = 'UPDATE_ANY_PROBLEM',
  DELETE_OWN_PROBLEM = 'DELETE_OWN_PROBLEM',
  DELETE_ANY_PROBLEM = 'DELETE_ANY_PROBLEM',

  // Tag
  CREATE_TAG = 'CREATE_TAG',
  UPDATE_ANY_TAG = 'UPDATE_ANY_TAG',
  DELETE_ANY_TAG = 'DELETE_ANY_TAG',

  // Role
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ANY_ROLE = 'UPDATE_ANY_ROLE',
  DELETE_ANY_ROLE = 'DELETE_ANY_ROLE',
}
