name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: install packages
        run: yarn install

      - name: check code
        uses: ./.github/actions/code-check

      - name: dist
        run: yarn run build

      - name: deploy
        uses: appleboy/scp-action@master
        with:
          host: 117.2.125.196
          port: 2222
          username: nguyenvu9405
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: 'dist'
          target: 'www/html'
          strip_components: 1
          rm: true
