name: Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  integration:
    runs-on: ubuntu-22.04

    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: install packages
        run: yarn install

      - name: check code
        uses: ./.github/actions/code-check
