# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install packages
        run: yarn install

      - name: lint
        run: yarn run lint

      - name: check compile
        run: yarn run check-compile

      - name: dist
        run: yarn run build
        
      - name: deploy
        uses: appleboy/scp-action@master
        with:
          host: 117.2.125.196
          username: nguyenvu9405
          password: Luctieu32
          port: 2222
          source: "dist"
          target: "www/html"
          strip_components: 1
