name: Nighly build

on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.sha }}
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/c-lab-frontend
  IMAGE_TAG: nightly-${{ github.sha }}

jobs:
  nightly-build:
    runs-on: ubuntu-20.04

    steps:
      - name: logging
        run: |
          echo build number: ${{ env.BUILD_NUMBER }}

      - name: check out
        uses: actions/checkout@v2

      - name: install packages
        run: yarn install

      - name: dist
        run: yarn run build
        
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

      - name: '[Deploy to server] login to docker'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.TESTING_SERVER_HOST }}
          port: ${{ vars.TESTING_SERVER_PORT }}
          username: ${{ vars.TESTING_SERVER_USERNAME }}
          key: ${{ secrets.TESTING_SERVER_SSH_KEY }}
          command_timeout: 30m
          script: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: '[Deploy to server] run the image'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.TESTING_SERVER_HOST }}
          port: ${{ vars.TESTING_SERVER_PORT }}
          username: ${{ vars.TESTING_SERVER_USERNAME }}
          key: ${{ secrets.TESTING_SERVER_SSH_KEY }}
          script: |
            cd ./c-lab-frontend
            docker compose down
            docker system prune -a -f
            export IMAGE_REPO=${{ env.IMAGE_REPO }} 
            export IMAGE_TAG=${{ env.IMAGE_TAG }} 
            docker compose up -d
