name: Deploy

on:
  push:
    tags:
      - v*

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/c-lab-frontend

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: set version
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: logging
        run: |
          echo ${{ env.RELEASE_VERSION }}

      - name: check out
        uses: actions/checkout@v2

      - name: install packages
        run: yarn install

      - name: dist
        run: yarn run build

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.RELEASE_VERSION }}

      - name: '[Deploy to server] login to docker'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SERVER_PORT }}
          username: ${{ vars.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: '[Deploy to server] run the image'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SERVER_PORT }}
          username: ${{ vars.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ./c-lab-frontend
            docker compose down
            docker system prune -a -f
            export IMAGE_REPO=${{ env.IMAGE_REPO }}  
            export IMAGE_TAG=${{ env.RELEASE_VERSION }} 
            docker compose up -d
