name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: set version
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: logging
        run: |
          echo ${{ env.RELEASE_VERSION }}

      - name: check out
        uses: actions/checkout@v2

      - name: install packages
        run: yarn install

      - name: dist
        run: yarn run build

      - name: configure amazon ecr account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: login to amazon ecr
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: build and push docker image
        id: build-image
        env:
          IMAGE_REPO: ${{ steps.login-ecr.outputs.registry }}/c-lab-frontend
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          docker build -t ${IMAGE_REPO}:${IMAGE_TAG} .
          docker push ${IMAGE_REPO}:${IMAGE_TAG}
          echo "image_repo=${IMAGE_REPO}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: '[Deploy to server] login to docker'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SERVER_PORT }}
          username: ${{ vars.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: >
            docker login ${{ steps.login-ecr.outputs.registry }}
            -u ${{ steps.login-ecr.outputs.docker_username_449313530982_dkr_ecr_us_east_2_amazonaws_com }}
            -p ${{ steps.login-ecr.outputs.docker_password_449313530982_dkr_ecr_us_east_2_amazonaws_com }}

      - name: '[Deploy to server] run the image'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SERVER_PORT }}
          username: ${{ vars.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ./c-lab-frontend
            docker compose down
            docker system prune -a -f
            export IMAGE_REPO=${{ steps.build-image.outputs.image_repo }} 
            export IMAGE_TAG=${{ steps.build-image.outputs.image_tag }} 
            docker compose up -d
